FROM ubuntu:18.04 as builder

ARG user=front-agent
ENV HOME="/home/$user"
WORKDIR $HOME
RUN mkdir -p .local/bin .local/etc .local/lib

# Install environment
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        automake \
        bison \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        flex \
        git \
        libbz2-dev \
        libffi-dev \
        libgmp-dev \
        liblzma-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-gplv2-dev \
        libsecp256k1-dev \
        libsqlite3-dev \
        libssl-dev \
        libtool \
        libzmq3-dev \
        pkg-config \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

ARG nacl_lib_ver=1.0.17

# Build and install libsodium library
RUN curl -o libsodium-${nacl_lib_ver}.tar.gz \
        "https://download.libsodium.org/libsodium/releases/libsodium-${nacl_lib_ver}.tar.gz" && \
    tar xzvf libsodium-${nacl_lib_ver}.tar.gz && \
    cd libsodium-${nacl_lib_ver} && \
    CFLAGS="-Os" ./configure && \
    make install && \
    cd .. && \
    cp -a /usr/local/lib/libsodium.so* "$HOME/.local/lib" && \
    rm -rf libsodium-${nacl_lib_ver}*

ENV LIBRARY_PATH="$HOME/.local/lib:$LIBRARY_PATH"

## Start fresh (new image) ##
FROM ubuntu:18.04

ARG uid=1001
ARG user=front-agent
ARG tag_name=front-agent
ARG tag_version=

ENV HOME="/home/$user" \
    APP_ROOT="$HOME" \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    SHELL=/bin/bash \
    SUMMARY="basic image based on ubuntu to build front agent later" \
    DESCRIPTION="This image provides a basic image to build the front agent. \
    Front agent will be connected to indy web service to communicate with \
    the hyperledger indy nodes."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="von-image $tag_version" \
      name="$tag_name" \
      version="$tag_version" \
      maintainer=""

# Add indy user
RUN useradd -U -ms /bin/bash -u $uid $user

# Install environment
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        bzip2 \
        curl \
        git \
        libffi6 \
        libgmp10 \
        liblzma5 \
        libncurses5 \
        libncursesw5 \
        libreadline5 \
        libsecp256k1-0 \
        libzmq5 \
        net-tools \
        openssl \
        sqlite3 \
        vim-tiny \
        zlib1g && \
    rm -rf /var/lib/apt/lists/* /usr/share/doc/*

WORKDIR $HOME

COPY --chown=front-agent:front-agent bin/ $HOME/.local/bin/
RUN chmod ug+rwx $HOME/.local/bin/*

# - In order to drop the root user, we have to make some directories writable
#   to the root group as OpenShift default security model is to run the container
#   under random UID.
RUN usermod -a -G 0 front-agent

USER $user

CMD ["bash"]
